# This workflow deploys the GitHub pages
name: deploy github pages

# This workflow is triggered on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # The job is named 'deploy'
  deploy:
    # The job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    # The concurrency group is defined by the workflow and the ref
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # The repository is checked out
      - uses: actions/checkout@v2

      # mdBook is set up
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      # The book is built
      - run: mdbook build

      # The book is deployed if the workflow is running on main.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book